fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
    tftp: "git://github.com/puppetlabs/puppetlabs-tftp"
    xinetd: "git://github.com/puppetlabs/puppetlabs-xinetd"
    epel: "git://github.com/stahnma/puppet-module-epel"
  symlinks:
    edeploy: "#{source_dir}"
